server:
  port: 3901
spring:
  application:
    name: MCPGateway
  ai:
    mcp:
      server:
        name: mcpgateway
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/messages
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: your_username
    password: your_password
    driver-class-name: com.mysql.jdbc.Driver